Allow use custom gomplate
RasaHQ/rasa-train-test-gha pull request #9
Opened 2021-08-16 11:04 UTC by HotThoughts

2021-08-16 12:46 UTC, HotThoughts commented
@tczekajlo This PR is ready for review. Please 👀 if you have time.

2021-08-24 06:57 UTC, tczekajlo requested changes

2021-08-24 06:57 UTC, tczekajlo commented on action.yml
> +        echo DOCKER_ARGS="--rm --tmpfs ${{ inputs.tmpfs_directory }} -e MPLCONFIGDIR=/tmp/.mplconfigdir \
I'd add `-e HOME=/app` as well.

2021-08-24 08:49 UTC, HotThoughts commented on action.yml
> +        echo DOCKER_ARGS="--rm --tmpfs ${{ inputs.tmpfs_directory }} -e MPLCONFIGDIR=/tmp/.mplconfigdir \
Added 👍🏻

2021-08-24 11:48 UTC, tczekajlo approved these changes
LGTM 🎖️

2021-08-24 11:48 UTC, merged